config/routes.rb
Rails.application.routes.draw do

  get 'ads/index'
  get 'ads/show'

  resources :messages

  resources :ads do
    resource  :user
    resources :messages do
      resource :reply
    end
  end

  devise_for :users
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  root 'application#home'
end

app/models/ad.rb
class Ad < ActiveRecord::Base
  belongs_to :user
  has_many   :messages


  def sent_messages current_user_id # you can skip sending user_id if you have a access to current user in models
    messages.where(user_id: current_user_id)
  end
end

app/models/message.rb
class Message < ActiveRecord::Base
  belongs_to :ad
  belongs_to :user
end

app/models/reply.rb
class Reply < ActiveRecord::Base
  belongs_to :user
  belongs_to :message

  after_update :send_mail

  validates_presence_of :text

  scope :approved, -> { where(is_approved: true) }

  private
  def send_mail
    if is_approved_changed? && is_approved
      UserMailer.new_reply_email(self).deliver_later
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :ads
  has_many :messages
  has_many :replies
end

app/controllers/ads_controller.rb
class AdsController < ApplicationController
  before_action :set_ad, only: [:show]

  # GET /ads
  # GET /ads.json
  def index
    @my_ads = current_user.ads
    @ads    = Ad.all
  end

  # GET /ads/1
  # GET /ads/1.json  
  def show
  end

  private

  def set_ad
    @ad = Ad.find(params[:id])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  # make sure user logged in before every action
  before_action :authenticate_user!

  # GET /
  # GET /home
  def home
    # load user ads
    @my_ads = current_user.ads

    # load all ads in system
    @ads    = Ad.all
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_message, only: [:show, :edit, :update, :destroy]
  before_action :set_ad

  # GET /messages
  # GET /messages.json
  def index
    @messages = Message.all
  end

  # GET /messages/1
  # GET /messages/1.json
  def show
  end

  # GET /messages/new
  def new
    @message = Message.new
  end

  # GET /messages/1/edit
  def edit
  end

  # POST /messages
  # POST /messages.json
  def create
    # @message = Message.new(message_params)
    @message = current_user.messages.new(ad_id: @ad.id, text: params[:message][:text])

    respond_to do |format|
      if @message.save
        # format.html { redirect_to :back, notice: 'Message was successfully posted.' }
        format.html { redirect_to ad_path(@ad.id), notice: 'Message was successfully created.' }
        format.json { render :show, status: :created, location: @message }
      else
        format.html { render :new }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /messages/1
  # PATCH/PUT /messages/1.json
  def update
    respond_to do |format|
      if @message.update(message_params)
        format.html { redirect_to ad_message_path(@ad.id, @message.id), notice: 'Message was successfully updated.' }
        format.json { render :show, status: :ok, location: @message }
      else
        format.html { render :edit }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /messages/1
  # DELETE /messages/1.json
  def destroy
    @message.destroy
    respond_to do |format|
      format.html { redirect_to ad_path(@ad.id), notice: 'Message was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_message
      @message = Message.find(params[:id])
    end

    def set_ad
      @ad = Ad.find(params[:ad_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def message_params
      # params.require(:message).permit(:ad_id, :sender_id, :receiver_id, :text, :is_approved)
      params.require(:message).permit(:text)
    end
end

app/controllers/replies_controller.rb
class RepliesController < ApplicationController
  before_action :set_ad # don't need actually, if we don't nest 3 level routes => ad > message > reply
  before_action :set_message
  before_action :set_reply, only: [:show, :edit, :update, :destroy]

  # GET /replies
  # GET /replies.json
  def index
    @replies = Reply.all
  end

  # GET /replies/1
  # GET /replies/1.json
  def show
  end

  # GET /replies/new
  def new
    @reply = Reply.new
  end

  # GET /replies/1/edit
  def edit
  end

  # POST /replies
  # POST /replies.json
  def create
    # @reply = Reply.new(reply_params)
    @reply = current_user.replies.new(message_id: @message.id, text: params[:reply][:text])

    respond_to do |format|
      if @reply.save
        format.html { redirect_to :back, notice: 'Reply was successfully sent.' }
        format.json { render :show, status: :created, location: @reply }
      else
        format.html { render :new }
        format.json { render json: @reply.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /replies/1
  # PATCH/PUT /replies/1.json
  def update
    respond_to do |format|
      if @reply.update(reply_params)
        format.html { redirect_to @reply, notice: 'Reply was successfully updated.' }
        format.json { render :show, status: :ok, location: @reply }
      else
        format.html { render :edit }
        format.json { render json: @reply.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /replies/1
  # DELETE /replies/1.json
  def destroy
    @reply.destroy
    respond_to do |format|
      format.html { redirect_to replies_url, notice: 'Reply was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ad
      @ad = Ad.find(params[:ad_id])
    end

    def set_message
      @message = Message.find(params[:message_id])
    end

    def set_reply
      @reply = Reply.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def reply_params
      params.require(:reply).permit(:text)
    end
end

app/helpers/ads_helper.rb
module AdsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/replies_helper.rb
module RepliesHelper
end

app/views/ads/index.html.erb
  <h2>My Ads</h2>
  <% @my_ads.each do |ad| %>
    <%= ad.title %> ... 
    <%= link_to 'view messages', ad_messages_path(ad) %>
    <br >
  <% end %>

  <hr>
  <h2>All Ads</h2>
  <% @ads.each do |ad| %>
    <%= ad.title %> ... 
    <%= link_to 'send message', new_ad_message_path(ad) %>
    <br >
  <% end %>

app/views/ads/show.html.erb
<p>Title: <%= @ad.title %></p>
<p>By: <%= @ad.user.email %></p>
<hr>

<% if current_user == @ad.user %>
  <h2>Received Messages:</h2>

  <% @ad.messages.approved.each do |message| %>
    <div class="message">
      <b><%= message.user.email %></b>: <span><%= message.text %></span>
      <br>
      <em><%= message.created_at %></em>
      <div>
        <% message.replies.approved.each do |reply| %>
          <div class="reply">
            <b>Me: </b><span><%= reply.text %></span>
          </div>
        <% end %>
      </div>
      <a href="#" class="reply_message" onclick="$('#reply_for_msg_<%= message.id %>').toggle();">Reply</a>
      <div id="reply_for_msg_<%= message.id %>" class="replies_form">
        <%= form_for Reply.new, url: ad_message_reply_path(@ad, message) do |f| %>
          <%= f.label :text %>
          <%= f.text_area :text %>
          <%= f.submit 'Reply' %>
        <% end %>
      </div>
    </div>
    <br>
  <% end %>
<% else %>
  <% @ad.sent_messages(current_user.id).each do |message| %>
    <div class="message">
      <b>Me: </b><span><%= message.text %></span>
      <br>
      <em><%= message.created_at %></em> - <b><%= message.is_approved ? 'Approved' : 'Pending Approval' %></b>
      <div>
        <% message.replies.approved.each do |reply| %>
          <div class="reply">
            <b><%= reply.user.email %>: </b><span><%= reply.text %></span>
          </div>
        <% end %>
      </div>      
    </div>
    <br>
  <% end %>

  <h1>New Message</h1>
  <% @message = Message.new %>
  <%= render 'messages/form' %>
  <%= link_to 'Back', ad_path(@ad) %>

<% end %>

app/views/application/home.html.erb
  <h2>My Ads</h2>
  <% @my_ads.each do |ad| %>
    <%= ad.title %> ... 
    <%= link_to 'view messages', ad_messages_path(ad) %>
    <br >
  <% end %>

  <hr>
  <h2>All Ads</h2>
  <% @ads.each do |ad| %>
    <%= ad.title %> ... 
    <%= link_to 'send message', new_ad_message_path(ad) %>
    <br >
  <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MessagingApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>

  <%= yield %>

  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
</body>
</html>

app/views/messages/_form.html.erb
<%= form_for [@ad, @message] do |f| %>
  <% if @message.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@message.errors.count, "error") %> prohibited this message from being saved:</h2>

      <ul>
      <% @message.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/messages/edit.html.erb
<h1>Editing Message</h1>

<%= render 'form' %>

<%= link_to 'Show', ad_message_path(@ad, @message) %> |
<%= link_to 'Back', ad_path(@ad) %>

app/views/messages/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Messages</h1>

<table>
  <thead>
    <tr>
      <th>Sender</th>
      <th>Text</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @messages.each do |message| %>
      <tr>
        <td><%= message.user.email %></td>
        <td><%= message.text %></td>
        <td><%= link_to 'Show', [@ad, message] %></td>
        <td><%= link_to 'Edit', edit_ad_message_path(@ad, message) %></td>
        <td><%= link_to 'Destroy', [@ad, message], method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Message', new_ad_message_path(@ad) %>

app/views/messages/new.html.erb
<h1>New Message</h1>

<%= render 'form' %>

<%= link_to 'Back', ad_path(@ad) %>

app/views/messages/show.html.erb
<p>
  <strong>Ad:</strong>
  <%= @message.ad.title %>
</p>

<p>
  <strong>Sender:</strong>
  <%= @message.user.email %>
</p>

<p>
  <strong>Text:</strong>
  <%= @message.text %>
</p>

<%= link_to 'Edit', edit_ad_message_path(@ad, @message) %> |
<%= link_to 'Back', ad_path(@ad) %>

app/views/replies/_form.html.erb
<%= form_for(@reply) do |f| %>
  <% if @reply.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@reply.errors.count, "error") %> prohibited this reply from being saved:</h2>

      <ul>
      <% @reply.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :message_id %><br>
    <%= f.number_field :message_id %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </div>
  <div class="field">
    <%= f.label :is_approved %><br>
    <%= f.check_box :is_approved %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/replies/edit.html.erb
<h1>Editing Reply</h1>

<%= render 'form' %>

<%= link_to 'Show', @reply %> |
<%= link_to 'Back', replies_path %>

app/views/replies/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Replies</h1>

<table>
  <thead>
    <tr>
      <th>Message</th>
      <th>User</th>
      <th>Text</th>
      <th>Is approved</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @replies.each do |reply| %>
      <tr>
        <td><%= reply.message_id %></td>
        <td><%= reply.user_id %></td>
        <td><%= reply.text %></td>
        <td><%= reply.is_approved %></td>
        <td><%= link_to 'Show', reply %></td>
        <td><%= link_to 'Edit', edit_reply_path(reply) %></td>
        <td><%= link_to 'Destroy', reply, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Reply', new_reply_path %>

app/views/replies/new.html.erb
<h1>New Reply</h1>

<%= render 'form' %>

<%= link_to 'Back', replies_path %>

app/views/replies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Message:</strong>
  <%= @reply.message_id %>
</p>

<p>
  <strong>User:</strong>
  <%= @reply.user_id %>
</p>

<p>
  <strong>Text:</strong>
  <%= @reply.text %>
</p>

<p>
  <strong>Is approved:</strong>
  <%= @reply.is_approved %>
</p>

<%= link_to 'Edit', edit_reply_path(@reply) %> |
<%= link_to 'Back', replies_path %>